// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { Knex } from 'knex';
import type { BookingInitializer, BookingMutator, default as Booking } from './public/Booking';
import type { CustomerInitializer, CustomerMutator, default as Customer } from './public/Customer';
import type { ProviderInitializer, ProviderMutator, default as Provider } from './public/Provider';
import type { ServiceTypeInitializer, ServiceTypeMutator, default as ServiceType } from './public/ServiceType';

declare module 'knex/types/tables' {
  interface Tables {
    'booking': Knex.CompositeTableType<Booking, BookingInitializer, BookingMutator>;
    'customer': Knex.CompositeTableType<Customer, CustomerInitializer, CustomerMutator>;
    'provider': Knex.CompositeTableType<Provider, ProviderInitializer, ProviderMutator>;
    'service_type': Knex.CompositeTableType<ServiceType, ServiceTypeInitializer, ServiceTypeMutator>;
  }
}
