const { Knex } = require('knex');

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
  return knex.raw(`
   CREATE EXTENSION IF NOT EXISTS citext;

   CREATE DOMAIN email AS citext
   CHECK (
           VALUE ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
          );
    CREATE TABLE provider(
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text NOT NULL,
      email email NOT NULL UNIQUE
    );
    `);
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
  return knex.raw(`
    DROP TABLE provider;
    DROP DOMAIN email;
    DROP EXTENSION citext;
    `);
};
